/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.digitalpc.calculadora;

/**
 *
 * @author mrsan
 */
public class CalculadoraSwing extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraSwing
     */
    public CalculadoraSwing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtN1Soma = new javax.swing.JTextField();
        txtN2Soma = new javax.swing.JTextField();
        txtDescricaoSoma = new javax.swing.JLabel();
        simboloSoma = new javax.swing.JLabel();
        lblSoma = new javax.swing.JLabel();
        btnClickSoma = new javax.swing.JButton();
        nomeDoPrograma = new javax.swing.JLabel();
        txtN1Subtracao = new javax.swing.JTextField();
        txtN2Subtracao = new javax.swing.JTextField();
        txtDescricaoSubtracao = new javax.swing.JLabel();
        btnClickSubtracao = new javax.swing.JButton();
        simboloSubtracao = new javax.swing.JLabel();
        lblSubtracao = new javax.swing.JLabel();
        txtN1Multiplicacao = new javax.swing.JTextField();
        txtN2Multiplicacao = new javax.swing.JTextField();
        txtDescricaoMultiplicacao = new javax.swing.JLabel();
        btnClickMultiplicacao = new javax.swing.JButton();
        simboloMultiplicacao = new javax.swing.JLabel();
        lblMultiplicacao = new javax.swing.JLabel();
        txtN1Divisao = new javax.swing.JTextField();
        txtN2Divisao = new javax.swing.JTextField();
        txtDescricaoDivisao = new javax.swing.JLabel();
        btnClickDivisao = new javax.swing.JButton();
        simboloDivisao = new javax.swing.JLabel();
        lblDivisao = new javax.swing.JLabel();
        enderecoGitHub = new javax.swing.JLabel();

        jTextField3.setText("jTextField3");

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("SUBTRAÇÃO");

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("=");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("+");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("0");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtN1Soma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtN1Soma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtN1SomaActionPerformed(evt);
            }
        });

        txtN2Soma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtDescricaoSoma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDescricaoSoma.setText("SOMA");

        simboloSoma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        simboloSoma.setText("+");

        lblSoma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSoma.setText("0.0");

        btnClickSoma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClickSoma.setText("=");
        btnClickSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClickSomaActionPerformed(evt);
            }
        });

        nomeDoPrograma.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nomeDoPrograma.setText("CALCULADORA");

        txtN1Subtracao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtN2Subtracao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtDescricaoSubtracao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDescricaoSubtracao.setText("SUBTRAÇÃO");

        btnClickSubtracao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClickSubtracao.setText("=");
        btnClickSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClickSubtracaoActionPerformed(evt);
            }
        });

        simboloSubtracao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        simboloSubtracao.setText("- ");

        lblSubtracao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSubtracao.setText("0.0");

        txtN1Multiplicacao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtN2Multiplicacao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtDescricaoMultiplicacao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDescricaoMultiplicacao.setText("MULTIPLICAÇÃO");

        btnClickMultiplicacao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClickMultiplicacao.setText("=");
        btnClickMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClickMultiplicacaoActionPerformed(evt);
            }
        });

        simboloMultiplicacao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        simboloMultiplicacao.setText("*");

        lblMultiplicacao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMultiplicacao.setText("0.0");

        txtN1Divisao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtN2Divisao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtDescricaoDivisao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDescricaoDivisao.setText("DIVISÃO");

        btnClickDivisao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClickDivisao.setText("=");
        btnClickDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClickDivisaoActionPerformed(evt);
            }
        });

        simboloDivisao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        simboloDivisao.setText("/");

        lblDivisao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDivisao.setText("0.0");

        enderecoGitHub.setText("https://github.com/mr-fabiosantos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nomeDoPrograma)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtDescricaoSoma)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtN1Soma, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(simboloSoma)
                                        .addGap(12, 12, 12)
                                        .addComponent(txtN2Soma, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(btnClickSoma)
                                .addGap(18, 18, 18)
                                .addComponent(lblSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDescricaoSubtracao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtN1Subtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(simboloSubtracao)
                                .addGap(12, 12, 12)
                                .addComponent(txtN2Subtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnClickSubtracao)
                                .addGap(18, 18, 18)
                                .addComponent(lblSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDescricaoMultiplicacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtN1Multiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(simboloMultiplicacao)
                                .addGap(12, 12, 12)
                                .addComponent(txtN2Multiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnClickMultiplicacao)
                                .addGap(18, 18, 18)
                                .addComponent(lblMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDescricaoDivisao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtN1Divisao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(simboloDivisao)
                                .addGap(12, 12, 12)
                                .addComponent(txtN2Divisao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnClickDivisao)
                                .addGap(18, 18, 18)
                                .addComponent(lblDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(enderecoGitHub)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomeDoPrograma)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtN1Soma, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtN2Soma, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescricaoSoma)
                    .addComponent(simboloSoma)
                    .addComponent(lblSoma)
                    .addComponent(btnClickSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtN1Subtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtN2Subtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescricaoSubtracao)
                    .addComponent(simboloSubtracao)
                    .addComponent(lblSubtracao)
                    .addComponent(btnClickSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtN1Multiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtN2Multiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescricaoMultiplicacao)
                    .addComponent(simboloMultiplicacao)
                    .addComponent(lblMultiplicacao)
                    .addComponent(btnClickMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtN1Divisao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtN2Divisao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescricaoDivisao)
                    .addComponent(simboloDivisao)
                    .addComponent(lblDivisao)
                    .addComponent(btnClickDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(enderecoGitHub)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtN1SomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtN1SomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtN1SomaActionPerformed

    private void btnClickSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClickSomaActionPerformed
        // Bloco de código para retorno da SOMA.
        float n1Soma = Float.parseFloat(txtN1Soma.getText());
        float n2Soma = Float.parseFloat(txtN2Soma.getText());
        float resultadoSoma = n1Soma + n2Soma;
        
        lblSoma.setText(Float.toString(resultadoSoma));
    }//GEN-LAST:event_btnClickSomaActionPerformed

    private void btnClickSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClickSubtracaoActionPerformed
        // Bloco de código para retorno da Subtração.
        float n1Sub = Float.parseFloat(txtN1Subtracao.getText());
        float n2Sub = Float.parseFloat(txtN2Subtracao.getText());
        float resultadoSub = n1Sub - n2Sub;
        
        lblSubtracao.setText(Float.toString(resultadoSub));
    }//GEN-LAST:event_btnClickSubtracaoActionPerformed

    private void btnClickMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClickMultiplicacaoActionPerformed
        // Bloco de código para retorno da Multiplicação.
        float n1Multi = Float.parseFloat(txtN1Multiplicacao.getText());
        float n2Multi = Float.parseFloat(txtN2Multiplicacao.getText());
        float resultadoMulti = n1Multi * n2Multi;
        
        lblMultiplicacao.setText(Float.toString(resultadoMulti));
    }//GEN-LAST:event_btnClickMultiplicacaoActionPerformed

    private void btnClickDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClickDivisaoActionPerformed
        // Bloco de código para retorno da Divisão.
        float n1Div = Float.parseFloat(txtN1Divisao.getText());
        float n2Div = Float.parseFloat(txtN2Divisao.getText());
        float resultadoDiv = n1Div / n2Div;
        
        lblDivisao.setText(Float.toString(resultadoDiv));
    }//GEN-LAST:event_btnClickDivisaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClickDivisao;
    private javax.swing.JButton btnClickMultiplicacao;
    private javax.swing.JButton btnClickSoma;
    private javax.swing.JButton btnClickSubtracao;
    private javax.swing.JLabel enderecoGitHub;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lblDivisao;
    private javax.swing.JLabel lblMultiplicacao;
    private javax.swing.JLabel lblSoma;
    private javax.swing.JLabel lblSubtracao;
    private javax.swing.JLabel nomeDoPrograma;
    private javax.swing.JLabel simboloDivisao;
    private javax.swing.JLabel simboloMultiplicacao;
    private javax.swing.JLabel simboloSoma;
    private javax.swing.JLabel simboloSubtracao;
    private javax.swing.JLabel txtDescricaoDivisao;
    private javax.swing.JLabel txtDescricaoMultiplicacao;
    private javax.swing.JLabel txtDescricaoSoma;
    private javax.swing.JLabel txtDescricaoSubtracao;
    private javax.swing.JTextField txtN1Divisao;
    private javax.swing.JTextField txtN1Multiplicacao;
    private javax.swing.JTextField txtN1Soma;
    private javax.swing.JTextField txtN1Subtracao;
    private javax.swing.JTextField txtN2Divisao;
    private javax.swing.JTextField txtN2Multiplicacao;
    private javax.swing.JTextField txtN2Soma;
    private javax.swing.JTextField txtN2Subtracao;
    // End of variables declaration//GEN-END:variables
}
